# Generated by Django 2.2.16 on 2020-10-16 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
